FROM python:3.6
MAINTAINER James Kizer <james@curiosityhealth.com>

ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
    apt-get -y install python curl unzip && cd /tmp && \
    curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip" && \
    unzip awscli-bundle.zip && \
    ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws && \
    rm awscli-bundle.zip && rm -rf awscli-bundle


#Add LDAP Support
RUN apt-get -y install build-essential python3-dev \
  libldap2-dev libsasl2-dev ldap-utils
  
# Add Microsoft repo for Microsoft ODBC Driver 13 for Linux
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/8/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update

# Install Dependencies
RUN ACCEPT_EULA=Y apt-get install -y \
    unixodbc \
    unixodbc-dev \
    libgss3 \
    odbcinst \
    msodbcsql \
    locales \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen

# install SQL Server tools
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y mssql-tools
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
RUN /bin/bash -c "source ~/.bashrc"

ADD . /src/

ENV LS2_BACKUP_HEALTH_CHECK_ENABLED False

RUN pip install -r /src/requirements.txt
RUN pip install -r /src/requirements.mssql.txt

RUN mkdir /etc/ls2
RUN mkdir /etc/ls2/settings
RUN touch /etc/ls2/settings/config.json

RUN mkdir /logs

WORKDIR /src
