# Generated by Django 2.0.1 on 2018-03-21 23:44

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='metadata',
            field=fernet_fields.fields.EncryptedTextField(blank=True, default=None, null=True),
        ),
    ]
