# Generated by Django 2.0.1 on 2018-03-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='participant_uuid',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='study_uuid',
            field=models.UUIDField(db_index=True, editable=False),
        ),
    ]
