# Generated by Django 2.0.1 on 2018-01-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='ap_source_name',
            field=models.CharField(max_length=128),
        ),
    ]
