# Generated by Django 2.0.1 on 2018-03-04 21:13

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0002_auto_20180118_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='encrypted_body',
            field=fernet_fields.fields.EncryptedTextField(default=''),
            preserve_default=False,
        ),
    ]
