# Generated by Django 2.0.1 on 2018-02-27 03:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0002_auto_20180118_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKeyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.CharField(max_length=5000)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveSmallIntegerField()),
                ('public_key_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study_management.Study')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='study_management.Study')),
            ],
        ),
    ]
