# Generated by Django 2.0.1 on 2018-03-23 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def insert_username(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    PasswordChangeEvent = apps.get_model("study_management", "PasswordChangeEvent")
    db_alias = schema_editor.connection.alias
    for event in PasswordChangeEvent.objects.all():
        if event.user != None:
            event.username = event.user.username
            event.save()

def reverse_username(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0003_participantaccountgenerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordchangeevent',
            name='username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordchangeevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(insert_username, reverse_username),
    ]
