# Generated by Django 2.0.1 on 2018-02-27 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0003_publickeyinfo_studyconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyconfiguration',
            name='public_key_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study_management.PublicKeyInfo'),
        ),
    ]
