# Generated by Django 2.0.1 on 2018-03-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0004_auto_20180323_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantAccountGenerationRequestEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('generator_id', models.UUIDField(blank=True)),
                ('remote_ip', models.CharField(db_index=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantAccountGenerationTimeout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('generator_id', models.UUIDField(blank=True)),
                ('disable_until', models.DateTimeField()),
                ('remote_ip', models.CharField(db_index=True, max_length=50, null=True)),
            ],
        ),
    ]
