# Generated by Django 2.0.1 on 2018-03-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0004_remove_datapoint_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapoint',
            old_name='encrypted_body',
            new_name='body',
        ),
    ]
