# Generated by Django 2.0.1 on 2018-02-27 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0004_auto_20180226_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publickeyinfo',
            old_name='created_date_time',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='studyconfiguration',
            old_name='created_date_time',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='study',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
