# Generated by Django 2.0.1 on 2018-02-27 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0005_auto_20180226_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyconfiguration',
            name='encrypt_by_deault',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studyconfiguration',
            name='public_key_info',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='study_management.PublicKeyInfo'),
        ),
    ]
