# Generated by Django 2.0.1 on 2018-02-27 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0006_auto_20180226_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyconfiguration',
            name='public_key_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='study_management.PublicKeyInfo'),
        ),
    ]
