# Generated by Django 2.1 on 2018-09-30 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0006_ldapusertoresearcherconverter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantAccountToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=50)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('expiration_date_time', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_date_time', models.DateTimeField(blank=True, null=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TokenBasedParticipantAccountGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username_prefix', models.CharField(blank=True, default='', max_length=16)),
                ('username_suffix', models.CharField(blank=True, default='', max_length=16)),
                ('username_random_character_length', models.PositiveSmallIntegerField(default=16)),
                ('password_min_length', models.PositiveSmallIntegerField(default=16)),
                ('password_max_length', models.PositiveSmallIntegerField(default=16)),
                ('token_format', models.CharField(choices=[('NM', 'Numeric'), ('AN', 'Alphanumeric'), ('64', 'Base64')], default='64', max_length=2)),
                ('token_size', models.PositiveSmallIntegerField(default=64)),
                ('token_lifetime', models.DurationField()),
                ('url_template', models.TextField(blank=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study_management.Study')),
            ],
        ),
        migrations.AddField(
            model_name='participantaccounttoken',
            name='account_generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study_management.TokenBasedParticipantAccountGenerator'),
        ),
    ]
