# Generated by Django 2.0.1 on 2018-02-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0007_auto_20180226_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publickeyinfo',
            name='data',
        ),
        migrations.AddField(
            model_name='publickeyinfo',
            name='contents',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
