# Generated by Django 2.1.3 on 2018-11-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_management', '0009_auto_20181001_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantaccountgenerator',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tokenbasedparticipantaccountgenerator',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
